# Generated by Django 5.2.6 on 2025-09-09 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_nombre', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuarios_app_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_app_permissions_set', to='auth.permission')),
                ('user_rol_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asp_nombre', models.CharField(max_length=100)),
                ('asp_apellido', models.CharField(max_length=100)),
                ('asp_correo', models.EmailField(max_length=254, unique=True)),
                ('asp_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('asp_departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('asp_ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('asp_ocupacion', models.CharField(blank=True, max_length=100, null=True)),
                ('asp_nacimiento_dia', models.IntegerField(blank=True, null=True)),
                ('asp_nacimiento_mes', models.IntegerField(blank=True, null=True)),
                ('asp_nacimiento_anio', models.IntegerField(blank=True, null=True)),
                ('asp_tipoId', models.CharField(blank=True, max_length=10, null=True)),
                ('asp_numeroId', models.CharField(blank=True, max_length=30, null=True)),
                ('asp_cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('asp_descripcion', models.TextField(blank=True, null=True)),
                ('asp_idiomas', models.JSONField(blank=True, null=True)),
                ('asp_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('asp_curriculum', models.FileField(blank=True, null=True, upload_to='curriculums/')),
                ('asp_foto', models.ImageField(blank=True, null=True, upload_to='fotos_aspirantes/')),
                ('asp_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_nombre', models.CharField(max_length=150)),
                ('em_nit', models.CharField(blank=True, max_length=50, null=True)),
                ('em_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('em_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('em_departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('em_ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('em_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('em_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('em_password', models.CharField(blank=True, max_length=128, null=True)),
                ('em_descripcion', models.TextField(blank=True, null=True)),
                ('em_sitioWeb', models.URLField(blank=True, null=True)),
                ('em_tamano', models.CharField(blank=True, max_length=50, null=True)),
                ('em_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('em_idiomas', models.JSONField(blank=True, null=True)),
                ('em_curriculum', models.FileField(blank=True, null=True, upload_to='empresas_docs/')),
                ('em_logo', models.ImageField(blank=True, null=True, upload_to='logos_empresas/')),
                ('em_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('chat_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
                ('chat_empleador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exes_nombreInstitucion', models.CharField(max_length=100)),
                ('exes_titulo', models.CharField(max_length=100)),
                ('exes_fechaInicio', models.DateField()),
                ('exes_fechaFin', models.DateField(blank=True, null=True)),
                ('exes_description', models.TextField(blank=True, null=True)),
                ('exes_nivelEducativo', models.CharField(blank=True, max_length=100, null=True)),
                ('exes_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exla_nombreEmpresa', models.CharField(max_length=100)),
                ('exla_cargo', models.CharField(max_length=100)),
                ('exla_fechaInicio', models.DateField()),
                ('exla_fechaFin', models.DateField(blank=True, null=True)),
                ('exla_salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exla_funcion', models.CharField(blank=True, max_length=255, null=True)),
                ('exla_descripcion', models.TextField(blank=True, null=True)),
                ('exla_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_contenido', models.TextField()),
                ('men_fecha', models.DateTimeField(auto_now_add=True)),
                ('men_chat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.chat')),
                ('men_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_contenido', models.CharField(max_length=255)),
                ('not_fecha', models.DateTimeField(auto_now_add=True)),
                ('not_estado', models.CharField(max_length=50)),
                ('not_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va_titulo', models.CharField(max_length=200)),
                ('va_requisitos', models.TextField()),
                ('va_salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('va_ubicacion', models.CharField(max_length=100)),
                ('va_descripcion', models.TextField()),
                ('va_estado', models.CharField(max_length=20)),
                ('va_idEmpresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_estado', models.CharField(max_length=50)),
                ('pos_fechaPostulacion', models.DateTimeField(auto_now_add=True)),
                ('pos_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
                ('pos_vacante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vacante')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_vacante_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vacante'),
        ),
    ]
