# Generated by Django 5.2.5 on 2025-08-23 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_nombre', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='usuarios_app_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='usuarios_app_permissions_set', to='auth.permission')),
                ('user_rol_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.rol')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_nombre', models.CharField(max_length=150)),
                ('em_sector', models.CharField(blank=True, max_length=100, null=True)),
                ('em_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('em_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('em_ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('em_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asp_nombre', models.CharField(max_length=100)),
                ('asp_apellido', models.CharField(max_length=100)),
                ('asp_correo', models.EmailField(max_length=254, unique=True)),
                ('asp_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('asp_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('asp_curriculum', models.CharField(blank=True, max_length=255, null=True)),
                ('asp_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
