# Generated by Django 5.2.5 on 2025-08-24 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rol_usuarios_empresa_aspirante_delete_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoSeleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ps_tipoEntrevista', models.CharField(max_length=100)),
                ('ps_modalidad', models.CharField(max_length=50)),
                ('ps_direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_estado', models.CharField(max_length=50)),
                ('ps_fechaPostulacion', models.DateTimeField(auto_now_add=True)),
                ('ps_idAspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
                ('ps_idEmpresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('va_titulo', models.CharField(max_length=200)),
                ('va_requisitos', models.TextField()),
                ('va_salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('va_ubicacion', models.CharField(max_length=100)),
                ('va_descripcion', models.TextField()),
                ('va_estado', models.CharField(max_length=20)),
                ('va_idEmpresa_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Vacante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dv_idAspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
                ('dv_idVacante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vacante')),
            ],
        ),
    ]
