# Generated by Django 4.2.24 on 2025-11-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_vacante_va_fecha_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='em_ciudad',
            new_name='em_barrio',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='em_departamento',
            new_name='em_localidad',
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_localidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
