# Generated by Django 5.2.5 on 2025-08-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuarios_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='asp_foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_aspirantes/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_curriculum',
            field=models.FileField(blank=True, null=True, upload_to='empresas_docs/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_empresas/'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='asp_curriculum',
            field=models.FileField(blank=True, null=True, upload_to='curriculums/'),
        ),
    ]
