# Generated by Django 4.2.24 on 2025-11-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_rename_em_ciudad_empresa_em_barrio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacante',
            name='va_categoria',
            field=models.CharField(choices=[('Tecnología', 'Tecnología'), ('Marketing', 'Marketing'), ('Finanzas', 'Finanzas'), ('Ventas', 'Ventas'), ('Administración', 'Administración'), ('Salud', 'Salud'), ('Educación', 'Educación'), ('Recursos Humanos', 'Recursos Humanos'), ('Diseño', 'Diseño'), ('Logística', 'Logística'), ('Servicio al Cliente', 'Servicio al Cliente'), ('Legal', 'Legal'), ('Construcción', 'Construcción'), ('Gastronomía', 'Gastronomía'), ('Manufactura', 'Manufactura'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
    ]
