# Generated by Django 5.2.5 on 2025-08-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_aspirante_asp_foto_empresa_em_curriculum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='asp_cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_idiomas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_nacimiento_anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_nacimiento_dia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_nacimiento_mes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_numeroId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='asp_tipoId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
