# Generated by Django 5.2.5 on 2025-08-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_aspirante_asp_cargo_aspirante_asp_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='em_estado',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='em_ubicacion',
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_idiomas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_nit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_sitioWeb',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_tamano',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='em_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
