# Generated by Django 5.2.5 on 2025-09-09 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_empresa_em_estado_remove_empresa_em_ubicacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procesoseleccion',
            name='ps_idAspirante_fk',
        ),
        migrations.RemoveField(
            model_name='procesoseleccion',
            name='ps_idEmpresa_fk',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('chat_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
                ('chat_empleador_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empresa')),
                ('chat_vacante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vacante')),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('resuelta', 'Resuelta')], max_length=20)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_denunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_reportado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncias_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exes_nombreInstitucion', models.CharField(max_length=100)),
                ('exes_titulo', models.CharField(max_length=100)),
                ('exes_fechaInicio', models.DateField()),
                ('exes_fechaFin', models.DateField(blank=True, null=True)),
                ('exes_description', models.TextField(blank=True, null=True)),
                ('exes_nivelEducativo', models.CharField(blank=True, max_length=100, null=True)),
                ('exes_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exla_nombreEmpresa', models.CharField(max_length=100)),
                ('exla_cargo', models.CharField(max_length=100)),
                ('exla_fechaInicio', models.DateField()),
                ('exla_fechaFin', models.DateField(blank=True, null=True)),
                ('exla_salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exla_funcion', models.CharField(blank=True, max_length=255, null=True)),
                ('exla_descripcion', models.TextField(blank=True, null=True)),
                ('exla_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_contenido', models.TextField()),
                ('men_fecha', models.DateTimeField(auto_now_add=True)),
                ('men_chat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.chat')),
                ('men_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_contenido', models.CharField(max_length=255)),
                ('not_fecha', models.DateTimeField(auto_now_add=True)),
                ('not_estado', models.CharField(max_length=50)),
                ('not_usuario_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_estado', models.CharField(max_length=50)),
                ('pos_fechaPostulacion', models.DateTimeField(auto_now_add=True)),
                ('pos_aspirante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aspirante')),
                ('pos_vacante_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.vacante')),
            ],
        ),
        migrations.DeleteModel(
            name='Detalle_Vacante',
        ),
        migrations.DeleteModel(
            name='ProcesoSeleccion',
        ),
    ]
